Add S3 Backup Policies
CloudAutomator/iam-policies pull request #41
Opened 2023-10-11 07:43 UTC by zhiren1211

「S3: バケットをバックアップ」に必要なIAMポリシーを追加しました

2023-10-11 08:14 UTC, zhiren1211 commented
@juno 
「S3: バケットをバックアップ」に必要なIAMポリシーを追加しました
ご確認お願いします:bow:

2023-10-12 03:57 UTC, juno requested changes
@zhiren1211 
`GetBucketLocation` の呼び出しも必要なあることがわかったので、S3のほうにそちらの追加もお願いできますか 🙏 
（仕様wikiには反映済みです）

- [GetBucketLocation \- Amazon Simple Storage Service](https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/API/API_GetBucketLocation.html)

2023-10-12 06:50 UTC, zhiren1211 commented
@juno
レビューありがとうございます！
再度、ご確認お願いします🙇

2023-10-12 07:04 UTC, juno approved these changes
👍

2023-10-12 07:04 UTC, merged